/**
 * @file community Schema
 * @author Lukas Courtney <lccourtney@ksu.edu>
 * @exports CommunitySchema the schema for the community model
 */

// Import libraries
import Sequelize from "sequelize";

/**
 * @swagger
 * components:
 *   schemas:
 *     Community:
 *       type: object
 *       properties:
 *         id:
 *           type: integer
 *           description: Autogenerated ID
 *         name:
 *           type: string
 *           description: The name of the community
 *         lat:
 *           type: number
 *           format: float
 *           description: The latitude of the community
 *         long:
 *           type: number
 *           format: float
 *           description: The longitude of the community
 *         owner_user_id:
 *           type: integer
 *           description: The ID of the user who owns the community
 *         county_id:
 *           type: integer
 *           description: The ID of the county where the community is located
 *         createdAt:
 *           type: string
 *           format: date-time
 *           description: When the community was created
 *         updatedAt:
 *           type: string
 *           format: date-time
 *           description: When the community was last updated
 *         metadata:
 *           type: array
 *           items:
 *             $ref: '#/components/schemas/Metadata'
 *       example:
 *         id: 1
 *         name: Example Community
 *         lat: 39.123456
 *         long: -94.123456
 *         owner_user_id: 1
 *         county_id: 1
 *         createdAt: 2025-02-04T15:36:32.000Z
 *         updatedAt: 2025-02-04T15:36:32.000Z
 */
const CommunitySchema = {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  name: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  lat: {
    type: Sequelize.FLOAT,
    allowNull: false,
  },
  long: {
    type: Sequelize.FLOAT,
    allowNull: false,
  },
  owner_user_id: {
    type: Sequelize.INTEGER,
    allowNull: false,
  },
  county_id: {
    type: Sequelize.INTEGER,
    allowNull: false,
  },
  createdAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
};

export default CommunitySchema;
