/**
 * @file county Schema
 * @author Lukas Courtney <lccourtney@ksu.edu>
 * @exports CountySchema the schema for the county model
 */

// Import libraries
import Sequelize from "sequelize";

/**
 * @swagger
 * components:
 *   schemas:
 *     County:
 *       type: object
 *       properties:
 *         id:
 *           type: integer
 *           description: Autogenerated id
 *         name:
 *           type: string
 *           description: The name of the county
 *         code:
 *           type: string
 *           description: The code for the county
 *         seat:
 *           type: string
 *           description: The seat of the county
 *         population:
 *           type: integer
 *           description: The population of the county
 *         est_year:
 *           type: integer
 *           description: The year the county was established
 *         createdAt:
 *           type: string
 *           format: date-time
 *           description: When the county was created
 *         updatedAt:
 *           type: string
 *           format: date-time
 *           description: When the county was last updated
 *         metadata:
 *           type: array
 *           items:
 *             $ref: '#/components/schemas/Metadata'
 *       example:
 *         id: 1
 *         name: Example County
 *         code: EX
 *         seat: Example City
 *         population: 100000
 *         est_year: 1900
 *         createdAt: 2025-02-04T15:36:32.000Z
 *         updatedAt: 2025-02-04T15:36:32.000Z
 */
const CountySchema = {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  name: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  code: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  seat: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  population: {
    type: Sequelize.INTEGER,
    allowNull: false,
  },
  est_year: {
    type: Sequelize.INTEGER,
    allowNull: false,
  },
  createdAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
};

export default CountySchema;
