/**
 * @file Document Schema
 * @author Lukas Courtney <lccourtney@ksu.edu>
 * @exports DocumentSchema the schema for the Document model
 */

// Import libraries
import Sequelize from "sequelize";

/**
 * @swagger
 * components:
 *   schemas:
 *     Document:
 *       type: object
 *       required:
 *         - display_name
 *         - filename
 *         - size
 *         - type
 *       properties:
 *         id:
 *           type: integer
 *           description: Autogenerated id
 *         display_name:
 *           type: string
 *           description: The display name of the document
 *         filename:
 *           type: string
 *           description: The name of the file
 *         size:
 *           type: integer
 *           description: The size of the file
 *         type:
 *           type: string
 *           description: The MIME type of the file
 *         createdAt:
 *           type: string
 *           format: date-time
 *           description: When the document was created
 *         updatedAt:
 *           type: string
 *           format: date-time
 *           description: When the document was last updated
 *         metadata:
 *           type: array
 *           items:
 *             $ref: '#/components/schemas/Metadata'
 *       example:
 *         id: 1
 *         display_name: Example Document
 *         filename: example_document.pdf
 *         size: 102400
 *         type: application/pdf
 *         createdAt: 2025-02-04T15:36:32.000Z
 *         updatedAt: 2025-02-04T15:36:32.000Z
 */
const DocumentSchema = {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  display_name: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  filename: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  size: {
    type: Sequelize.INTEGER,
    allowNull: false,
  },
  type: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  createdAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
};

export default DocumentSchema;
