/**
 * @file Movement Schema
 * @author Lukas Courtney <lccourtney@ksu.edu>
 * @exports MovementSchema the schema for the Movement model
 */

// Import Libraries
import Sequelize from "sequelize";

/**
 * @swagger
 * components:
 *   schemas:
 *     Movement:
 *       type: object
 *       properties:
 *         id:
 *           type: integer
 *           description: autogenerated id
 *         createdAt:
 *           type: string
 *           format: date-time
 *           description: when the movement was created
 *         updatedAt:
 *           type: string
 *           format: date-time
 *           description: when the movement was last updated
 *       example:
 *         id: 1
 *         createdAt: 2025-02-04T15:36:32.000Z
 *         updatedAt: 2025-02-04T15:36:32.000Z
 */
const MovementSchema = {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  createdAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
};

export default MovementSchema;
