/**
 * @file Order Schema
 * @author Lukas Courtney <lccourtney@ksu.edu>
 * @exports OrderSchema the schema for the Order model
 */

// Import Libraries
import Sequelize from "sequelize";

/**
 * @swagger
 * components:
 *   schemas:
 *     Order:
 *       type: object
 *       properties:
 *         id:
 *           type: integer
 *           description: autogenerated id
 *         createdAt:
 *           type: string
 *           format: date-time
 *           description: when the order was created
 *         updatedAt:
 *           type: string
 *           format: date-time
 *           description: when the order was last updated
 *       example:
 *         id: 1
 *         createdAt: 2025-02-04T15:36:32.000Z
 *         updatedAt: 2025-02-04T15:36:32.000Z
 */
const OrderSchema = {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  createdAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
};

export default OrderSchema;
