/**
 * @file Product Schema
 * @author Lukas Courtney <lccourtney@ksu.edu>
 * @exports ProductSchema the schema for the Product model
 */

// Import libraries
import Sequelize from "sequelize";

/**
 * @swagger
 * components:
 *   schemas:
 *     Product:
 *       type: object
 *       required:
 *         - supplierId
 *         - typeId
 *         - sizeId
 *         - caseSize
 *       properties:
 *         id:
 *           type: integer
 *           description: autogenerated id
 *         supplierId:
 *           type: integer
 *           description: supplier id
 *         typeId:
 *           type: integer
 *           description: product type id
 *         sizeId:
 *           type: integer
 *           description: product size id
 *         caseSize:
 *           type: integer
 *           description: number of units per case
 *         description:
 *           type: string
 *           nullable: true
 *           description: product description
 *         createdAt:
 *           type: string
 *           format: date-time
 *           description: when the product was created
 *         updatedAt:
 *           type: string
 *           format: date-time
 *           description: when the product was last updated
 *       example:
 *         id: 1
 *         supplierId: 1
 *         typeId: 2
 *         sizeId: 3
 *         caseSize: 9
 *         description: supplier 2% milk
 *         createdAt: 2025-02-04T15:36:32.000Z
 *         updatedAt: 2025-02-04T15:36:32.000Z
 */
const ProductSchema = {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  supplierId: {
    type: Sequelize.INTEGER,
    allowNull: false,
    unique: "productComposite",
  },
  typeId: {
    type: Sequelize.INTEGER,
    allowNull: false,
    unique: "productComposite",
  },
  sizeId: {
    type: Sequelize.INTEGER,
    allowNull: false,
    unique: "productComposite",
  },
  caseSize: {
    type: Sequelize.INTEGER,
    allowNull: false,
  },
  description: {
    type: Sequelize.STRING,
    allowNull: true,
  },
  createdAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
};

export default ProductSchema;
