/**
 * @file ProductCount Schema
 * @author Lukas Courtney <lccourtney@ksu.edu>
 * @exports ProductCountSchema the schema for the ProductCount model
 */

//Import Libraries
import { Sequelize } from "sequelize";

/**
 * @swagger
 * components:
 *   schemas:
 *     ProductCount:
 *       type: object
 *       required:
 *         - productId
 *         - quantity
 *       properties:
 *         id:
 *           type: integer
 *           description: autogenerated id
 *         productId:
 *           type: integer
 *           description: product id
 *         quantity:
 *           type: integer
 *           description: quantity of the product
 *         createdAt:
 *           type: string
 *           format: date-time
 *           description: when the product count was created
 *         updatedAt:
 *           type: string
 *           format: date-time
 *           description: when the product count was last updated
 *       example:
 *         id: 1
 *         productId: 1
 *         quantity: 100
 *         createdAt: 2025-02-04T15:36:32.000Z
 *         updatedAt: 2025-02-04T15:36:32.000Z
 */
const ProductCountSchema = {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  productId: {
    type: Sequelize.INTEGER,
    allowNull: false,
    references: { model: "product", key: "id" },
    onDelete: "cascade",
  },
  quantity: {
    type: Sequelize.INTEGER,
    allowNull: false,
  },
  createdAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
};

export default ProductCountSchema;
