/**
 * @file ProductType model
 * @author Lukas Courtney <lccourtney@ksu.edu>
 * @exports ProductTypeSchema the schema for the ProductType model
 */

// Import libraries
import Sequelize from "sequelize";

/**
 * @swagger
 * components:
 *   schemas:
 *     ProductType:
 *       type: object
 *       required:
 *         - type
 *       properties:
 *         id:
 *           type: integer
 *           description: autogenerated id
 *         type:
 *           type: string
 *           description: product type name
 *         createdAt:
 *           type: string
 *           format: date-time
 *           description: when the product type was created
 *         updatedAt:
 *           type: string
 *           format: date-time
 *           description: when the product type was last updated
 *       example:
 *         id: 1
 *         type: beverage
 *         createdAt: 2025-02-04T15:36:32.000Z
 *         updatedAt: 2025-02-04T15:36:32.000Z
 */
const ProductTypeSchema = {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  type: {
    type: Sequelize.STRING,
    allowNull: false,
    uniqueKey: true,
  },
  createdAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
};

export default ProductTypeSchema;
