/**
 * @file ProductSize model
 * @author Lukas Courtney <lccourtney@ksu.edu>
 * @exports ProductSizeSchema the schema for the ProductSize model
 */

// Import libraries
import Sequelize from "sequelize";

/**
 * @swagger
 * components:
 *   schemas:
 *     ProductSize:
 *       type: object
 *       required:
 *         - ounces
 *       properties:
 *         id:
 *           type: integer
 *           description: autogenerated id
 *         ounces:
 *           type: integer
 *           description: size in ounces
 *         commonName:
 *           type: string
 *           nullable: true
 *           description: common name for the size
 *         createdAt:
 *           type: string
 *           format: date-time
 *           description: when the product size was created
 *         updatedAt:
 *           type: string
 *           format: date-time
 *           description: when the product size was last updated
 *       example:
 *         id: 1
 *         ounces: 16
 *         commonName: pint
 *         createdAt: 2025-02-04T15:36:32.000Z
 *         updatedAt: 2025-02-04T15:36:32.000Z
 */
const ProductSizeSchema = {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  ounces: {
    type: Sequelize.INTEGER,
    allowNull: false,
    uniqueKey: true,
  },
  commonName: {
    type: Sequelize.STRING,
    allowNull: true,
    uniqueKey: true,
  },
  createdAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
};

export default ProductSizeSchema;
