/**
 * @file Supplier model
 * @author Lukas Courtney <lccourtney@ksu.edu>
 * @exports MovementTypeSchema the schema for the supplier model
 */

// Import libraries
import Sequelize from "sequelize";

/**
 * @swagger
 * components:
 *   schemas:
 *     Supplier:
 *       type: object
 *       required:
 *         - name
 *         - address
 *         - description
 *       properties:
 *         id:
 *           type: integer
 *           description: autogenerated id
 *         name:
 *           type: string
 *           description: supplier name
 *         address:
 *           type: string
 *           description: supplier address
 *         description:
 *           type: string
 *           description: supplier description
 *         createdAt:
 *           type: string
 *           format: date-time
 *           description: when the supplier was created
 *         updatedAt:
 *           type: string
 *           format: date-time
 *           description: when the supplier was last updated
 *       example:
 *         id: 1
 *         name: example supplier
 *         address: earth
 *         description: i sell things
 *         createdAt: 2025-02-04T15:36:32.000Z
 *         updatedAt: 2025-02-04T15:36:32.000Z
 */
const SupplierSchema = {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  name: {
    type: Sequelize.STRING,
    allowNull: false,
    uniqueKey: true,
  },
  address: {
    type: Sequelize.STRING,
    allowNull: false,
    uniqueKey: true,
  },
  description: {
    type: Sequelize.STRING,
    allowNull: false,
    uniqueKey: true,
  },
  createdAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
};

export default SupplierSchema;
