/**
 * @file Metadata Schema
 * @author Lukas Courtney <lccourtney@ksu.edu>
 * @exports MetadataSchema the schema for the Metadata model
 */

// Import libraries
import Sequelize from "sequelize";

/**
 * @swagger
 * components:
 *   schemas:
 *     Metadata:
 *       type: object
 *       required:
 *         - title
 *         - author
 *         - publisher
 *         - date
 *         - abstract
 *         - citation
 *         - copyright_id
 *         - keywords
 *         - owner_user_id
 *       properties:
 *         id:
 *           type: integer
 *           description: Autogenerated id
 *         title:
 *           type: string
 *           description: The title of the work
 *         author:
 *           type: string
 *           description: The author of the work
 *         publisher:
 *           type: string
 *           description: The publisher of the work
 *         date:
 *           type: string
 *           format: date-time
 *           description: The publication date
 *         abstract:
 *           type: string
 *           description: A brief summary of the work
 *         citation:
 *           type: string
 *           description: Citation details for the work
 *         copyright_id:
 *           type: integer
 *           description: The copyright id
 *         keywords:
 *           type: string
 *           description: Keywords associated with the work
 *         owner_user_id:
 *           type: integer
 *           description: The ID of the owner user
 *         createdAt:
 *           type: string
 *           format: date-time
 *           description: When the record was created
 *         updatedAt:
 *           type: string
 *           format: date-time
 *           description: When the record was last updated
 *       example:
 *         id: 1
 *         title: "Example Title"
 *         author: "Dr. Example"
 *         publisher: "Example Publisher"
 *         date: "2025-02-04T15:36:32.000Z"
 *         abstract: "Example abstract"
 *         citation: "Example Citation"
 *         copyright_id: 1001
 *         keywords: "very, cool, metadata"
 *         owner_user_id: 1
 *         createdAt: "2025-02-04T15:36:32.000Z"
 *         updatedAt: "2025-02-04T15:36:32.000Z"
 */
const MetadataSchema = {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  title: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  author: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  publisher: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  date: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  abstract: {
    type: Sequelize.TEXT,
    allowNull: false,
  },
  citation: {
    type: Sequelize.TEXT,
    allowNull: false,
  },
  copyright_id: {
    type: Sequelize.INTEGER,
    allowNull: false,
  },
  keywords: {
    type: Sequelize.STRING,
    allowNull: false,
  },
  owner_user_id: {
    type: Sequelize.INTEGER,
    allowNull: false,
  },
  createdAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
  updatedAt: {
    type: Sequelize.DATE,
    allowNull: false,
  },
};

export default MetadataSchema;
